# Generated by Django 5.2.14 on 2026-05-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExploreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='explore/audio')),
                ('transcription', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='explore/images')),
                ('published', models.BooleanField(default=False, help_text='Only published Explore Items will appear on the public web interface')),
                ('admin_notes', models.TextField(blank=True, help_text='Optional. Used for internal notes. Only visible on this page and will not appear on public website.', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lastupdated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
