# Generated by Django 5.2.6 on 2025-09-30 06:25

import ckeditor_uploader.fields
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, unique=True)),
                ('image', models.ImageField(upload_to='news-articleimages')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('admin_published', models.BooleanField(default=False, help_text='Only published articles will appear on the public interface', verbose_name='published')),
                ('admin_notes', models.TextField(blank=True, help_text='Optional. Used for internal notes. Only visible on this page and will not appear on public website.', null=True)),
                ('meta_created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('meta_lastupdated_datetime', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('meta_firstpublished_datetime', models.DateTimeField(blank=True, null=True, verbose_name='First Published')),
                ('meta_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='article_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('meta_lastupdated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='article_lastupdated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('title'), 'id'],
            },
        ),
    ]
