# Generated by Django 5.2.10 on 2026-03-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_article_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='videos',
            field=models.TextField(blank=True, help_text='Paste embed code from YouTube. Include multiple videos on new lines.', null=True),
        ),
    ]
